### ISSUE TITLE
Analytics empty data

### ISSUE THREAD

**Issue by jorgesanchezperez** [OpenBankingToolkit/openbanking-analytics#201]
### Description
The analytics UI doesn't show any data about `usage endpoints` and `psu counter` because the below entries in mongodb are empty:
- endpointUsageEntry
- psuCounterEntry

Other UI components don't show data in the analytic APP.
### Task
- [x] Investigate empty entries.
- [x] Investigate UI components don't show data in the app.
- [x] Apply a fix to store the entries data
- [x] Prepare upgrade step class for the next deployment version.

**Comment by jorgesanchezperez** [comment]
### Investigation result
#### endpoitUsageEntry empty
The current version of the rest api controller `EndpointUsageKpiAPIController` from `analytics core module` from [analytics](https://github.com/OpenBankingToolkit/openbanking-analytics) used to save the entries sent by any service (as-api, rs-ui, etc etc) using the Filter `MetricFilter` from [clients](https://github.com/OpenBankingToolkit/openbanking-clients) doesn't use any more the repository `EndpointUsageEntriesRepository` to save the object entry `EndpointUsageEntry`.

```java
/* Before ob-reference-implementation (forgecloud) commit 603a0c0e */
/* date 10/06/2019 */
/* Class com.forgerock.openbanking.metrics.api.endpoint.EndpointUsageKpiAPIController */
private void saveEntries(List<EndpointUsageEntry> endpointUsageEntries) {
        endpointUsageEntries.forEach(endpointUsageEntryEnricher::enrich);
        endpointUsageEntriesRepository.saveAll(endpointUsageEntries);
        endpointUsageAggregator.aggregate(endpointUsageEntries);
}
/* Current version on open banking tool kit */ 
public void saveEntries(List<EndpointUsageEntry> endpointUsageEntries) {
        endpointUsageEntries.forEach(endpointUsageEntryEnricher::enrich);
        endpointUsageAggregator.aggregate(endpointUsageEntries);
}
```
> It means that currently the `endpointUsageEntry` will be empty in mongodb always because never is saved any entry.
**This changes seems to be related with performance improvements.**
#### Suggested Solutions
1. Update analytics to consume the data from `endpointUsageAggregate`.
1. Hide the UI section where must show the `endpointUsageEntry` data.
1. Reimplement the use of repository `EndpointUsageEntriesRepository` to save again the `endpointUsageEntry` and avoid the empty data.

**Comment by jorgesanchezperez** [comment]
## Investigation: _Investigate UI components don't show data in the app._
## Results
### UI General Service Usage Tab
#### Component: _Number of endpoint calls by Open Banking API versions_
The UI consume the metric service to get the data and to do that each request contains `sort`, `filters` and `fields` and the service make a data filter and build an aggregation data using these values.
- Sometimes the `Request` contains values that don't exist and the aggregation data it's null.
   - Example: Filter by `ob version`, the `endpointUsageAggregate` doesn't have that field but must have it, the problem it's related with the annotation class `OpenBankingAPI` used in `MetricFilter`  ([clients](https://github.com/OpenBankingToolkit/openbanking-clients)), this class doesn't match with the origin class used to annotate the controllers in aspsp, it's duplicated using different packages in different projects.
```java
    OpenBankingAPI annotation = AnnotationUtils.findAnnotation(handler.getBeanType(), OpenBankingAPI.class);
```
And the below source never works to find the values on the annotation class, superclass or interfaces.
```java
    @Override
    @SuppressWarnings("unchecked")
    public <A extends Annotation> A getDeclaredAnnotation(Class<A> annotationClass) {
        Objects.requireNonNull(annotationClass);

        return (A) annotationData().declaredAnnotations.get(annotationClass);
    }
```
### Solution
- Create a new module to centralise the annotations on `openbanking-commons` named `forgerock-openbanking-annotations` and move all openbanking custom annotation `OpenBankingAPI` to the new module.
- Make a refactor on all classes to replace and to use the new annotations library from `openbanking-commons` through all repositories that use the annotations.

**Comment by jorgesanchezperez** [comment]
## Investigation: _Investigate UI components don't show data in the app._
## Results
### TAB UI: _Read/Write APIs menu_ / _Payments APIs_
#### Components:
- _Payments endpoints called by OIDC clients_

The query return empty data because the entry `consentStatusEntry` doesn't have any document that match with the filter:
```json
{ "consentType": "PAYMENT_FILE_CONSENT" }
```
### Tasks
- [ ] Investigate why the consent file payment is not being saved in the analytics entry such as the others.
- [ ] Fix to save the payment file consent in the analytics entry properly.

**Comment by jorgesanchezperez** [comment]
## Investigation: _Investigate UI components don't show data in the app._
### TAB UI: _Read/Write APIs menu_ / _Confirmation of funds APIs_
#### Components:
- **ALL UI components empty**
### Task
- [ ] Investigate all UI components
##
### TAB UI: _Read/Write APIs menu_ / _Events notification APIs_
#### Components:
- **ALL UI components empty**
### Task
- [ ] Investigate all UI components
